# Generated by Django 5.1.5 on 2025-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("type_of_document", models.CharField(max_length=255)),
                ("institution", models.CharField(max_length=255)),
                ("specialization", models.BooleanField()),
                ("date", models.DateField()),
                ("paid", models.BooleanField()),
                ("provider", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
