# Generated by Django 5.1.5 on 2025-02-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_alter_record_paid_alter_record_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="paid",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="specialization",
            field=models.BooleanField(),
        ),
    ]
