# Generated by Django 5.1.5 on 2025-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_record_thumbnail_alter_record_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="paid",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="specialization",
            field=models.CharField(max_length=255),
        ),
    ]
